### ISSUE TITLE
Problem running in wayland.

### ISSUE THREAD

**Issue by machadofguilherme** [Adamcake/Bolt#10]
As the title says, the game is completely frozen. Is there any way to configure an environment variable so that the game runs normally? I tried changing the "data/bolt-launcher/Jagex/launcher/preferences.cfg" file but without any success.

**Comment by Adamcake** [comment]
Hi, which game are you trying to run - RS3, Runelite, or HDOS?

Have you been able to get that game to run by any other means, such as directly installing its flatpak repo?

How did you install Bolt? (flatpak, AUR, other..?)

**Comment by Adamcake** [comment]
Ah, are you using an Nvidia GPU?

**Comment by machadofguilherme** [comment]
Intel. More specifically...:

Memory: 3.7 GiB
Processor: Intel® Core™ i5-8250U × 8
Graphics: Software Rendering
Disk capacity: 1.0 TB
GNOME Version: 45.1
Window system: Wayland
Kernel check: Linux 6.6.7-gentoo-dist

An addendum: In the x11 session, the game only ran correctly after I installed the "xf86-video-intel" package. Maybe this information will help you in some way.

**Comment by Adamcake** [comment]
Okay that's interesting. This issue is known to happen with nvidia + wayland + rs3, but I've never heard of it happening with intel before. For completeness's sake I'll point out that I've just tried launching the game in wayland, in gentoo on my AMD GPU, and that works fine.

You might like to try updating to Bolt version 0.7 which was released today, which adds wayland access to the flatpak package. It would be a sheer coincidence if that fixed the problem, but worth a try. You'd also want to set `SDL_VIDEODRIVER=wayland` in your environment.

Assuming that doesn't help, I should have some time tomorrow to try out intel+gentoo and see what happens.

**Comment by machadofguilherme** [comment]
Version 0.7.0 is working with Wayland!!

However, it is consuming a lot of resources on my machine. Is it because it is an unstable version?
Would it be possible for you to generate a new updated Flatpak package?

**Comment by machadofguilherme** [comment]
It worked fine once.

After that I restarted the system, added that environment variable and it didn't work.

I compiled version 0.7.0.
I also had a problem with high resource consumption.

**Comment by machadofguilherme** [comment]
Did not work. Even after adding the environment variable.

I compiled version 0.7, as you suggested.
I have the Vulkan packages installed in addition to Mesa and LLVM. Everything updated.

I also had a problem with high resource consumption.
You can get an idea by looking at the screenshot below as to why the image looks strange.
![image](https://github.com/Adamcake/Bolt/assets/33203070/d54407b5-0f7f-46a4-8e23-a63968febe77)

**Comment by Adamcake** [comment]
Ah okay, well at least you were able to get in-game. You mentioned you were using "software rendering", what exactly do you mean? If this is being rendered entirely on the GPU then I'd expect it to look something like that, and it would explain the high/maxed CPU usage.

**Comment by machadofguilherme** [comment]
Regarding rendering, I just copied and pasted the information contained in "gnome-control-center". To be more precise, I have an Intel integrated GPU.

What catches my attention is that in the section with Xorg, I can play smoothly. The characters move, everything is fluid.

For some reason I don't know, in the section with Wayland the game becomes unplayable.

Just to clarify that information, I took it from here (this is data that GNOME provides in relation to hardware):
![image](https://github.com/Adamcake/Bolt/assets/33203070/1e5491e2-95d4-439b-b9c0-6c04b4d9a7b2)

**Comment by Adamcake** [comment]
If you switch to X11, and see the game run smoothly, what does that menu show?

**Comment by machadofguilherme** [comment]
By the way, would my make.conf file be of any use?
Or an emerge --info to see the active flags on the system?
It could be that I didn't configure something correctly.

On x11, the menu shows the following:
![image](https://github.com/Adamcake/Bolt/assets/33203070/7e119b2d-9534-4a0b-bbf6-62e62e813d7e)

**Comment by Adamcake** [comment]
Well there's the problem then. On X11 it's using the GPU, but on Wayland for whatever reason it's unable to use the GPU and is rendering without it. You'll have this same problem with almost any game.

It's probably a missing dependency or feature but there's not much I can do to help here since it's unrelated to this game or launcher.

**Comment by machadofguilherme** [comment]
Don't ask me what I did, I don't even understand, but the game is running wonderfully on GNOME with Wayland. I think I fixed the problem after leaving the system updating last night.

In any case, thank you very much for your availability. =D
