### ISSUE TITLE
AUR package has problems with Arch default environment variables

### ISSUE THREAD

**Issue by vaisest** [Adamcake/Bolt#29]
I installed the AUR package and encountered a couple of issues:

1. Runelite links such as login or the Discord button do not work, fixed by setting `XDG_*` envvars
2. OSHD launch complains about `JAVA_HOME`

As far as I know by default none of these are set in Arch. `JAVA_HOME` used to be set, but it seems Arch just sets PATH with the  `archlinux-java` script.  The XDG variables are, as far as I know, supposed [to have defaults when they are not set](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html).

They are also mentioned in [the Arch wiki](https://wiki.archlinux.org/title/XDG_Base_Directory), and after launching with `~ $ XDG_CONFIG_HOME=$HOME/.config XDG_CACHE_HOME=$HOME/.cache XDG_DATA_HOME=$HOME/.local/share XDG_STATE_HOME=$HOME/.local/state bolt` Runelite links seem to function.

Are the XDG variables perhaps not being set by default? #21 is possibly about the same issue.

**Comment by Adamcake** [comment]
> Runelite links such as login or the Discord button do not work, fixed by setting XDG_* envvars

Already fixed in f3a7b5a awaiting next version, what you mentioned is the workaround for now

> OSHD launch complains about `JAVA_HOME`

This is due to a workaround I made to get HDOS to work on Java 17+. (see [fake_java.c](https://github.com/Adamcake/Bolt/blob/8c7c6c96bbc44ee0f3086d4ca36cf26d2f00ab9e/src/fake_java.c)). The HDOS devs don't have a clue what they're doing with regards to fixing issues, so my ability to improve the situation is quite limited... Frankly it's a miracle HDOS works at all under these conditions.

**Comment by vaisest** [comment]
Oh, I  didn't realise that was fixed already. I'll use the git version in the meantime, thanks
