### ISSUE TITLE
Legacy Java Client 

### ISSUE THREAD

**Issue by j0esmama32** [Adamcake/Bolt#31]
Is it possible to have the legacy java client added to the launcher as a launch option alongside RuneLite/HDOS?

**Comment by Adamcake** [comment]
Well in that case I can look at adding this, pending the UI rework in #30. I want to add the official Windows C++ clients for OSRS and RS3 as well, which all have very similar download-and-installation methods, so it'll save me some time to do them all at once.

**Comment by TormStorm** [comment]
It still works, but it’s effectively discontinued as you can’t download it from the Jagex launcher anymore, so eventually no-one will be able to use it, not that many people use it anyways. It could be added as on option, at least until Jagex actually stops supporting it. Adding the new official client would be very nice with all of the upcoming features which I’m very much looking forward to trying out.

**Comment by j0esmama32** [comment]
I personally still use it which is why I asked if it could be added. 
As far as I know it is still downloadable via their website. Having the new C++ client would be nice too in the future if they plan totally stop supporting the java client.

**Comment by Espionage724** [comment]
Can download the Legacy Java client here (official DL page -> scroll down to Game Direct Download): https://oldschool.runescape.com/download?force_test=control

Windows: https://www.runescape.com/downloads/oldschool.msi

Not sure what Bolt is doing, but when running Jagex Launcher through Wine, a symlink from osclient.exe (official C++) to system Java and launching the OSRS legacy jar and even RuneLite's Jar works and logs in.

It's still officially supported and works fine today July 2024 (install JL and the OldSchool MSI for the option to show in JL on Windows). I prefer the Legacy Java client over the C++ one [because the C++ client is brighter/less-saturated](https://realmofespionage.blogspot.com/2024/05/old-school-runescape-legacy-java-client.html).

**Comment by Adamcake** [comment]
It also doesn't support jagex accounts according to this post so it
wouldn't work with a launcher anyway.

**Comment by j0esmama32** [comment]
> It also doesn't support jagex accounts according to this post so it wouldn't work with a launcher anyway.
Not sure why they said this, it works for me with a Jagex account & Jagex launcher on windows.  
I guess this issue can be closed now following this news.

**Comment by Adamcake** [comment]
It's quite a shame, I only figured out where all the official clients are
updated from a few weeks ago, so I actually could have added this in the
next version... but probably not a good idea now.
