### ISSUE TITLE
Tray Icon Not Appearing in Wayland

### ISSUE THREAD

**Issue by dotaxis** [Adamcake/Bolt#33]
Hi, I run Arch with Hyprland and this is a minor annoyance but when I launch RuneLite via Bolt I tend to exit Bolt right after with my keyboard shortcut.

Unfortunately, there is no tray icon or "exit" button in Bolt, and the process stays running unless I kill it with `pkill -9 bolt`.

I'm not sure if there's supposed to be a tray icon that is not appearing in Hyprland, and that's the reason it stays running in the background, but it is a minor annoyance of mine. I don't like to keep the Bolt window open once I've launched RuneLite.

Would be great to have an "exit" button in Bolt that clean exits and/or fix the minimize to tray functionality (if that is indeed supposed to be a feature).

**Comment by Adamcake** [comment]
There is indeed supposed to be a tray icon. It's created using the deprecated tray functions in gtk3 since that's what Chromium/CEF has, so I'm not surprised that it doesn't work on a Wayland system.

You're not the first to complain about the tray icon. I'm planning to remove it in the next version.

**Comment by dotaxis** [comment]
I appreciate the quick response.

For what it's worth, I don't hate the idea of a tray icon if you can get it working on Wayland, but it's up to you if you would rather remove it and find some other solution for the RS3 stuff.

I will rename this issue now that I know the actual cause :)

**Comment by tarlacac** [comment]
As an additional note, I am using Manjaro/Gnome with X11 instead of Wayland and am seeing the same issue. I click the "X" button to close Bolt and the process doesn't exit until I kill the process on the terminal. Gnome hasn't supported tray icons for a while apparently, so Bolt just disappears into the aether instead of closing.

I'm just glad to finally know why this is happening! You're doing great with Bolt btw! I use it on my desktop and Steamdeck, as do my other Linux and Steamdeck friends, to get RuneLite anywhere easily.

**Comment by Adamcake** [comment]
Fixed in 0.9, there's no longer a tray icon and the process exits itself when appropriate.
